[workspace]
members = ["crates/icy_sixel", "crates/icy_sixel-cli"]
exclude = ["crates/icy_sixel/fuzz"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/mkrueger/icy_sixel"
